# Site settings
title: A brief intro about me
description: A brief intro about me
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Koshik Raj
user_description: Hello there, not to boast, but I'am clear logical thinker. I design algorithms for every problem in my life unknowingly. I like to solve lot of puzzles (Yeah! I'am a speed cuber as well) and learn new technologies.
user_title: Security and Blockchain Enthusiast
email: koshik.raj@gmail.com
twitter_username: rajkoshik
github_username:  koshikraj
quora_username:  Koshik-Raj

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
